hhData <- read.csv2("household_power_consumption.txt", header = TRUE,  dec = ".",sep=';',stringsAsFactors=FALSE,na.strings='?')
hhData$Date <- as.Date(hhData$Date,'%d/%m/%Y')
hhData <- subset(hhData,hhData$Date>= as.Date('2007-02-01') & hhData$Date<= as.Date('2007-02-02'))
png(filename = "plot4.png",  width = 480, height = 480, units = "px")
Sys.setlocale("LC_TIME", "English")
t<-as.POSIXct(paste(hhData$Date, hhData$Time))
par(mfrow = c(2,2))
plot(t,hhData$Global_active_power,type = 'l',xlab = NA,ylab = 'Global active power (kilowatts)')
plot(t,hhData$Voltage,type = 'l',xlab = NA,ylab = 'Voltage')
plot(t,hhData$Sub_metering_1,type = 'l',xlab = NA,ylab = 'Energy sub metering')
lines(t,hhData$Sub_metering_2,col = 'red')
lines(t,hhData$Sub_metering_3,col = 'blue')
legend('topright',names(hhData[7:9]),lty = c(1,1,1),col = c('black','red','blue'))
plot(t,hhData$Global_reactive_power,type = 'l',xlab = NA,ylab = 'Global_reactive_power')
dev.off()
