hhData <- read.csv2("household_power_consumption.txt", header = TRUE,  dec = ".",sep=';',stringsAsFactors=FALSE,na.strings='?')
hhData$Date <- as.Date(hhData$Date,'%d/%m/%Y')
hhData <- subset(hhData,hhData$Date>= as.Date('2007-02-01') & hhData$Date<= as.Date('2007-02-02'))
png(filename = "plot1.png",  width = 480, height = 480, units = "px")
hist(hhData$Global_active_power,main = 'Gloabal Active Power',xlab = 'Global Active Power(Killowatts)',col = 'red')
dev.off()
